---
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
  become: true

- name: restart redis_exporter
  service:
    name: redis_exporter
    state: restarted
  become: true

- name: restart postgres_exporter
  service:
    name: postgres_exporter
    state: restarted
  become: true

- name: restart mysql_exporter
  service:
    name: mysql_exporter
    state: restarted
  become: true

- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted
  become: true

- name: restart statsd_exporter
  service:
    name: statsd_exporter
    state: restarted
  become: true

- name: restart elasticsearch_exporter
  service:
    name: elasticsearch_exporter
    state: restarted
  become: true
